# Generated by Django 4.2 on 2024-09-11 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('code', models.CharField(blank=True, default=None, max_length=5, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Код программы лояльности')),
                ('card_number', models.CharField(blank=True, default=None, max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер карты должен быть указан в формате: 0000 0000 0000 0000', regex='\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')], verbose_name='Номер карты лояльности')),
            ],
        ),
    ]
