# Generated by Django 4.2 on 2024-09-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loyaltest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyalty',
            old_name='loyalty_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='loyalty',
            name='loyalty_url',
        ),
        migrations.RemoveField(
            model_name='loyalty',
            name='survey_children',
        ),
        migrations.RemoveField(
            model_name='loyalty',
            name='survey_repair',
        ),
    ]
