# Generated by Django 4.2 on 2024-10-02 14:54

import birthday.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=birthday.fields.BirthdayField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 13 символов.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Ваш номер телефона'),
        ),
    ]
