# Generated by Django 4.2 on 2024-09-11 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_loyalty_code_loyalty_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='card_number',
            field=models.CharField(blank=True, default=None, max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер карты должен быть указан в формате: 0000 0000 0000 0000', regex='\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')], verbose_name='Номер карты лояльности'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Код программы лояльности'),
        ),
    ]
