# Generated by Django 4.2 on 2024-10-04 11:16

from django.db import migrations, models
import users.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_by_code',
            field=models.CharField(blank=True, default=None, help_text='При регистрации пользователь указал код друга посоветовавшего сайт.', max_length=5, null=True, verbose_name='Код лояльности друга'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активный пользователь', verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-10-04', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-10-04', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='code',
            field=models.CharField(blank=True, default=None, help_text='(Не обязательное поле. Номер карты создается автоматически.)\nФормат: FS5Kl. Только заглавные латинские буквы и цифры.', max_length=5, null=True, unique=True, validators=[users.validations.code_validation], verbose_name='Код программы лояльности'),
        ),
    ]
