# Generated by Django 4.2 on 2024-09-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_loyaltyoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Выгода', 'verbose_name_plural': 'Выгода'},
        ),
        migrations.AddField(
            model_name='benefit',
            name='status',
            field=models.CharField(choices=[('Оповещение отправлено', 'Послано автоматическое оповещение на почту сотрудников'), ('Принято в работу', 'Сотрудник оповещен, выдачи выгоды в процессе'), ('Завершен', 'Выгода выдана')], default='Оповещение отправлено', help_text='Три статуса процесса выдачи награды. При автоматическом начислении бонусов автоматически "Завершен"', max_length=150, verbose_name='Статус выдачи выбранной выгоды'),
        ),
        migrations.CreateModel(
            name='LoyaltyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.benefit', verbose_name='Выбранная выгода')),
                ('loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.loyalty', verbose_name='Лояльность')),
            ],
            options={
                'verbose_name': '(m2m) Выбранная выгода',
                'verbose_name_plural': '(m2m) Выбранная выгода',
            },
        ),
        migrations.AddField(
            model_name='loyalty',
            name='benefits',
            field=models.ManyToManyField(related_name='benefits', through='users.LoyaltyBenefit', to='users.benefit', verbose_name='Выбранная выгода'),
        ),
    ]
