# Generated by Django 4.2 on 2024-10-09 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=None, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 13 символов.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Номер телефона'),
        ),
    ]
