# Generated by Django 4.2 on 2024-09-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_benefit_options_benefit_status_loyaltybenefit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='status',
        ),
        migrations.AddField(
            model_name='loyaltybenefit',
            name='status',
            field=models.CharField(choices=[('Оповещение отправлено', 'Послано автоматическое оповещение на почту сотрудников'), ('Принято в работу', 'Сотрудник оповещен, выдачи выгоды в процессе'), ('Завершен', 'Выгода выдана')], default='Оповещение отправлено', help_text='Три статуса процесса выдачи награды. При автоматическом начислении бонусов автоматически "Завершен"', max_length=150, verbose_name='Статус выдачи выбранной выгоды'),
        ),
    ]
