# Generated by Django 4.2 on 2024-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_benefit_status_loyaltybenefit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='time_created',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Заголовок или сокращенная информация'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-13', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-13', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
    ]
