# Generated by Django 4.2 on 2024-10-10 13:42

import birthday.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=birthday.fields.BirthdayField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 13 символов.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-10-10', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-10-10', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
    ]
