# Generated by Django 4.2 on 2024-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_loyalty_time_created_alter_benefit_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-17', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-17', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='loyaltybenefit',
            name='status',
            field=models.CharField(choices=[('Оповещение отправлено', 'Послано автоматическое оповещение на почту сотрудников'), ('Принято в работу', 'Сотрудник оповещен, выдача выгоды в процессе'), ('Завершен', 'Выгода выдана')], default='Оповещение отправлено', help_text='Три статуса процесса выдачи награды. Если выбрали начисление бонусов автоматически "Завершен"', max_length=150, verbose_name='Статус выдачи выбранной выгоды'),
        ),
    ]
