# Generated by Django 4.2 on 2024-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_loyalty_balance_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='new_befit',
        ),
        migrations.AddField(
            model_name='loyalty',
            name='new_befits',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Автоматически высчитывает количество доступных выборов.', verbose_name='(Тех)Количество доступных выборов'),
        ),
    ]
