# Generated by Django 4.2 on 2024-10-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_loyalty_balance_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltybenefit',
            options={'verbose_name': '(m2m) (m2m) Выбранная выгода', 'verbose_name_plural': '(m2m) Выбранная выгода'},
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='\nРегистрация в системе лояльности 2024-10-12', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='\nРегистрация в системе лояльности 2024-10-12', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
    ]
