# Generated by Django 4.2 on 2024-09-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_loyalty_new_befit_loyalty_new_befits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='new_befits',
        ),
    ]
