# Generated by Django 4.2 on 2024-09-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_loyalty_new_befits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-19', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-19', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
        migrations.AlterField(
            model_name='loyaltybenefit',
            name='benefit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.benefit', verbose_name='Выбранная выгода'),
        ),
        migrations.AlterField(
            model_name='loyaltybenefit',
            name='status',
            field=models.CharField(choices=[('Оповещение отправлено', 'Послано автоматическое оповещение на почту сотрудников'), ('Принято в работу', 'Сотрудник оповещен, выдача выгоды в процессе'), ('Завершен', 'Выгода выдана'), ('Отклонена', 'Отклонена')], default='Оповещение отправлено', help_text='Три статуса процесса выдачи награды. Если выбрали начисление бонусов автоматически "Завершен"', max_length=150, verbose_name='Статус выдачи выбранной выгоды'),
        ),
    ]
