# Generated by Django 4.2 on 2024-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_loyalty_balance_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='new_befits',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Автоматически оповещает пользователя о доступном выборе', verbose_name='(Тех)Количество выбора выгод'),
        ),
    ]
