# Generated by Django 4.2 on 2024-09-19 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_loyalty_new_befits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltybenefit',
            name='id',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='bonuses_to_add',
            field=models.PositiveIntegerField(default=0, help_text='Количество бонус для автоматического начисления после выбора выгоды. Ограничение 30000', validators=[django.core.validators.MaxValueValidator(30000)], verbose_name='Автоматически начислить бонусов'),
        ),
        migrations.AlterField(
            model_name='loyaltybenefit',
            name='loyalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.loyalty', verbose_name='Лояльность'),
        ),
    ]
