# Generated by Django 4.2 on 2024-09-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_loyaltybenefit_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltybenefit',
            name='loyalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.loyalty', verbose_name='Лояльность'),
        ),
    ]
