# Generated by Django 4.2 on 2024-09-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_loyaltybenefit_loyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltybenefit',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-20', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-20', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
        migrations.AlterField(
            model_name='loyaltybenefit',
            name='loyalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.loyalty', verbose_name='Лояльность'),
        ),
    ]
