# Generated by Django 4.2 on 2024-09-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_loyaltybenefit_id_alter_loyalty_balance_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='new_befits',
        ),
    ]
