# Generated by Django 4.2 on 2024-09-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_loyalty_new_befits'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='friends_loyalty',
            field=models.ForeignKey(blank=True, default=None, help_text='Чужим кодом можно воспользоваться лишь раз.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.loyalty', verbose_name='(Тех)Использованный код друга'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='bonus_from_reference',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Автоматически начисляется если другой пользователь зарегистрировался и прошел опросник.При достижении 5000 рублей, оповещает пользователя и сотрудника о возможности обменять бонусы на деньги.', verbose_name='(Тех)Бонусы полученные с приглашения на регистрацию'),
        ),
    ]
