# Generated by Django 4.2 on 2024-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_loyalty_friends_loyalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='friends_loyalty',
        ),
        migrations.AddField(
            model_name='loyalty',
            name='friends_loyalty_used',
            field=models.BooleanField(blank=True, default=False, help_text='Чужим кодом можно воспользоваться лишь раз.', verbose_name='(Тех)Использован код друга'),
        ),
    ]
