# Generated by Django 4.2 on 2024-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_loyalty_friends_loyalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyalty',
            name='balance_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-24', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя', verbose_name='(Тех)Статистика бонусного счета'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='benefits_history',
            field=models.TextField(blank=True, default='Регистрация в системе лояльности 2024-09-24', help_text='В данном тексте будет автоматически сохраняться история выбора выгод пользователя, и получение бонусов за приглашение нового пользователя.', verbose_name='(Тех)История выбора выгод счета'),
        ),
    ]
