# Generated by Django 4.2 on 2024-09-27 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Ответ')),
                ('user_answer', models.BooleanField(default=False, help_text='Если True, то вариант был написан пользователем', verbose_name='Ответ написан пользователем')),
            ],
            options={
                'verbose_name': '(Тех)Answer',
                'verbose_name_plural': '(Тех)Answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '(m2m)AnswerQuestionAndAnswer',
                'verbose_name_plural': '(m2m)AnswerQuestionAndAnswers',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Дополнительная информация')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 13 символов.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Ваш номер телефона')),
                ('contact_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Как с Вами связаться?')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ваша ссылка на Telegram/ВКонтакте')),
                ('date_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата и время встречи')),
                ('python_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Для теста перевода формата времени из js в python')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки пользователей',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание мебели')),
                ('price', models.PositiveIntegerField(default=1, verbose_name='Стоимость')),
                ('model_3d', models.CharField(blank=True, default='В РАЗРАБОТКЕ', max_length=20000, null=True, verbose_name='3D модель готовой мебели')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Готовая мебель для ознакомления',
            },
        ),
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория готовой мебели',
                'verbose_name_plural': 'Категории готовой мебели',
            },
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Изображение для мебели',
                'verbose_name_plural': 'Изображения для мебели',
            },
        ),
        migrations.CreateModel(
            name='FurnitureTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Тег мебели',
                'verbose_name_plural': 'Теги для мебели',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Титульная часть новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('extra_url', models.URLField(blank=True, default='', verbose_name='Ссылка на внешний источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта ответа')),
                ('user_input', models.BooleanField(default=False, help_text='Если True, пользователь сможет ввести свой вариант ответа', verbose_name='Вариант пользователя')),
            ],
            options={
                'verbose_name': '(Тех)Option',
                'verbose_name_plural': '(Тех)Options',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_code', models.CharField(blank=True, default=None, help_text='Если покупатель совершает заказ с использованием чужого кода лояльности, владелец кода автоматически оповещается о возможности выбора выгоды', max_length=5, null=True, verbose_name='Чужой код лояльности')),
                ('number', models.CharField(max_length=150, verbose_name='Номер заказа')),
                ('create_date', models.DateField(null=True, verbose_name='Дата заказа')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('Выезд замерщика', 'Выезд замерщика'), ('Подготовка эскиза', 'Подготовка эскиза'), ('Монтаж', 'Монтаж'), ('Выполнен', 'Выполнен'), ('Отклонен', 'Отклонен')], default='1', max_length=100, verbose_name='Статус заказа')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('contract', models.FileField(blank=True, upload_to='contracts', verbose_name='Договор')),
                ('model_3d', models.CharField(blank=True, default='3d code', max_length=20000, null=True, verbose_name='3D модель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Изображение для заказа',
                'verbose_name_plural': 'Изображения для заказа',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Оригинальное изображение')),
                ('image_medium', models.ImageField(blank=True, default=None, help_text='Не загружать!', upload_to='', verbose_name='Уменьшенное х2(Загрузка не требуется)')),
                ('image_small', models.ImageField(blank=True, default=None, help_text='Не загружать!', upload_to='', verbose_name='Уменьшенное х5(Загрузка не требуется)')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('only_one_image', models.BooleanField(blank=True, default=False, help_text='Для готовой мебели опцию оставлять отключенной! Для всего остального включать(это сократит занятое место на диске сервера)', verbose_name='Создать только одно изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('multy_choice', models.BooleanField(default=False, help_text='При включении этой опции позволяет опрашиваемому выбрать несколько вариантов', verbose_name='Выбрать несколько ответов')),
            ],
            options={
                'verbose_name': 'Вопрос с вариантами ответа',
                'verbose_name_plural': 'Вопросы с вариантами ответа',
            },
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '(Тех)QuestionAndAnswer',
                'verbose_name_plural': '(Тех)QuestionAndAnswers',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Рекомендовать к этой мебели',
                'verbose_name_plural': 'Рекомендовать к этой мебели',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependable', models.BooleanField(default=True, help_text='Статус становится положительным в случае если опросник заполняли больше минимального времени заполнения. При аналитике ненадежные будут вычеркиваться из выборки', verbose_name='Опросник надежен')),
                ('questions_was_changed', models.BooleanField(blank=True, default=False, help_text='Данный статус автоматически изменяется если были изменения в опроснике(как случай, добавление новых вопросов)\nЕсли есть новые вопросы пользователь должен будет вновь пройти опрос', verbose_name='Опросник был изменен')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата опроса')),
            ],
            options={
                'verbose_name': 'Опрос пользователя',
                'verbose_name_plural': 'Опросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('highlight', models.BooleanField(default=False, verbose_name='Визуальное выделение')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Все настройки', max_length=100, verbose_name='')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('min_write_time', models.PositiveIntegerField(default=30, help_text='Минимальное количество времени, требуемое для заполнение опросника. Если опросник был заполнен быстрее, он будет помечен как неблагонадежный. Неблагонадежные опросники будут исключаться из аналитики.', verbose_name='Мин. время заполнения опросника(сек)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
