# Generated by Django 4.2 on 2024-09-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Istok_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='similarfurniture',
            name='instance_furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_furniture', to='Istok_app.furniture'),
        ),
        migrations.AddField(
            model_name='similarfurniture',
            name='similar_furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_furniture', to='Istok_app.furniture'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.option'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.question'),
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='answers',
            field=models.ManyToManyField(related_name='answers', through='Istok_app.AnswerQuestionAndAnswer', to='Istok_app.answer'),
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Istok_app.survey', verbose_name='Опросник'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='options', through='Istok_app.QuestionOption', to='Istok_app.option'),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.order'),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='order_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.projectimage'),
        ),
        migrations.AddField(
            model_name='order',
            name='images',
            field=models.ManyToManyField(related_name='order_images', through='Istok_app.OrderImage', to='Istok_app.projectimage', verbose_name='Изображение заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='furnituretags',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.furniture'),
        ),
        migrations.AddField(
            model_name='furnituretags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.tags'),
        ),
        migrations.AddField(
            model_name='furnitureimage',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.furniture'),
        ),
        migrations.AddField(
            model_name='furnitureimage',
            name='project_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.projectimage'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.furniturecategory', verbose_name='Категория мебели'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='images',
            field=models.ManyToManyField(related_name='furniture_images', through='Istok_app.FurnitureImage', to='Istok_app.projectimage', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='recommendations',
            field=models.ManyToManyField(blank=True, through='Istok_app.SimilarFurniture', to='Istok_app.furniture', verbose_name='Список рекомендаций'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='Istok_app.FurnitureTags', to='Istok_app.tags', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='answerquestionandanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.answer'),
        ),
        migrations.AddField(
            model_name='answerquestionandanswer',
            name='question_and_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.questionandanswer'),
        ),
        migrations.AddConstraint(
            model_name='questionandanswer',
            constraint=models.UniqueConstraint(fields=('survey', 'question'), name='survey_question'),
        ),
        migrations.AddConstraint(
            model_name='orderimage',
            constraint=models.UniqueConstraint(fields=('order', 'order_image'), name='order_order_image'),
        ),
        migrations.AddConstraint(
            model_name='furnituretags',
            constraint=models.UniqueConstraint(fields=('furniture', 'tag'), name='furniture_tag'),
        ),
        migrations.AddConstraint(
            model_name='furnitureimage',
            constraint=models.UniqueConstraint(fields=('furniture', 'project_image'), name='furniture_project_image'),
        ),
    ]
