# Generated by Django 4.2 on 2024-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='body_material',
            field=models.CharField(choices=[('1', 'ЛДСП'), ('2', 'МДФ'), ('3', 'Пленка ПВХ'), ('4', 'Пластик AGT'), ('5', 'Пластик Fenix'), ('6', 'Эмаль')], default='1', max_length=2, verbose_name='Материал корпуса'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='facades_material',
            field=models.CharField(choices=[('1', 'ЛДСП'), ('2', 'МДФ'), ('3', 'Пленка ПВХ'), ('4', 'Пластик AGT'), ('5', 'Пластик Fenix'), ('6', 'Эмаль')], default='1', max_length=2, verbose_name='Материал фасадов'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Стоимость'),
        ),
    ]
