# Generated by Django 4.2 on 2024-10-10 19:19

import Istok_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contract',
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=150, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='multy_choice',
            field=models.BooleanField(default=False, help_text='При включении этой опции позволяет опрашиваемому выбрать несколько вариантов', verbose_name='Можно выбрать несколько'),
        ),
        migrations.CreateModel(
            name='DocumentForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=Istok_app.models.document_path, verbose_name='Документ')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
