# Generated by Django 4.2 on 2024-07-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0002_alter_furniture_body_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='color_hex',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='furniture',
            name='form',
            field=models.CharField(choices=[('0', 'Нет данных'), ('1', 'Прямая'), ('2', 'Г-образная'), ('3', 'П-образная'), ('4', 'С барной стойкой'), ('5', 'С островом')], default='1', max_length=1, verbose_name='Форма мебели'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='type',
            field=models.CharField(choices=[('1', 'Гардероб'), ('2', 'Стол'), ('3', 'Комод'), ('4', 'Тумбочка'), ('5', 'Шкаф')], default='1', max_length=1, verbose_name='Тип мебели'),
        ),
        migrations.CreateModel(
            name='FurniturePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.furniture')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.purpose')),
            ],
        ),
        migrations.AddField(
            model_name='furniture',
            name='purpose',
            field=models.ManyToManyField(through='Istok_app.FurniturePurpose', to='Istok_app.purpose'),
        ),
    ]
