# Generated by Django 4.2 on 2024-10-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0003_remove_order_contract_alter_order_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfororder',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы заказа'},
        ),
    ]
