# Generated by Django 4.2 on 2024-07-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0003_purpose_rename_color_color_color_hex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='tabletop_material',
            field=models.CharField(choices=[('1', 'ЛДСП'), ('2', 'МДФ'), ('3', 'Пленка ПВХ'), ('4', 'Пластик AGT'), ('5', 'Пластик Fenix'), ('6', 'Эмаль')], default='1', max_length=2, verbose_name='Материал столешницы'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', through='Istok_app.FurnitureTags', to='Istok_app.tags'),
        ),
    ]
