# Generated by Django 4.2 on 2024-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0004_furniture_tabletop_material_alter_furniture_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
