# Generated by Django 4.2 on 2024-10-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0004_alter_documentfororder_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentForOrder',
            new_name='Order_Document',
        ),
    ]
