# Generated by Django 4.2 on 2024-10-10 22:24

import Istok_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0005_rename_documentfororder_order_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Istok_app.models.document_path, verbose_name='Оригинальное изображение')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '(тех)Изображение',
                'verbose_name_plural': '(тех)Изображения заказов',
                'ordering': ['-time_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='order_document',
            options={'ordering': ['-time_created'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы заказа'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='images',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Выезд замерщика', 'Выезд замерщика'), ('Подготовка эскиза', 'Подготовка эскиза'), ('Монтаж', 'Монтаж'), ('Выполнен', 'Выполнен'), ('Отклонен', 'Отклонен')], default='Создан', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.DeleteModel(
            name='OrderImage',
        ),
        migrations.AddField(
            model_name='order_image',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.order', verbose_name='Заказ'),
        ),
    ]
