# Generated by Django 4.2 on 2024-07-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0005_alter_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='name',
        ),
    ]
