# Generated by Django 4.2 on 2024-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0006_rename_tag_tags_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='text',
            field=models.TextField(default='Описание мебели'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='form',
            field=models.CharField(choices=[('0', 'Нет данных'), ('1', 'Прямая'), ('2', 'Г-образная'), ('3', 'П-образная'), ('4', 'С барной стойкой'), ('5', 'С островом')], default='1', max_length=2, verbose_name='Форма мебели'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='style',
            field=models.CharField(choices=[('1', 'Классика'), ('2', 'Современный'), ('3', 'Лофт'), ('4', 'Скандинавский'), ('5', 'Минимализм'), ('6', 'Хай-тек'), ('7', 'Прованс'), ('8', 'Кантри')], default='1', max_length=2, verbose_name='Стиль мебели'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='type',
            field=models.CharField(choices=[('1', 'Гардероб'), ('2', 'Стол'), ('3', 'Комод'), ('4', 'Тумбочка'), ('5', 'Шкаф')], default='1', max_length=2, verbose_name='Тип мебели'),
        ),
    ]
