# Generated by Django 4.2 on 2024-10-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0006_order_image_alter_order_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionandanswer',
            options={'verbose_name': '(Тех)Вопрос с Ответом', 'verbose_name_plural': '(Тех)Вопросы с Ответами'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions_was_changed',
        ),
    ]
