# Generated by Django 4.2 on 2024-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0007_furniture_text_alter_furniture_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='text',
            field=models.TextField(default='Описание мебели', verbose_name='Описание мебели'),
        ),
    ]
