# Generated by Django 4.2 on 2024-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0007_alter_questionandanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос для опросника', 'verbose_name_plural': 'Вопросы для опросника'},
        ),
        migrations.AddField(
            model_name='survey',
            name='new_questions',
            field=models.TextField(blank=True, default='', verbose_name='(тех)Список id на неотвеченные вопросы'),
        ),
    ]
