# Generated by Django 4.2 on 2024-10-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0008_alter_question_options_survey_new_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='new_questions',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='(тех)Список id на неотвеченные вопросы'),
        ),
    ]
