# Generated by Django 4.2 on 2024-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0008_alter_furniture_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='purpose',
        ),
        migrations.AddField(
            model_name='furniture',
            name='purposes',
            field=models.ManyToManyField(related_name='purposes', through='Istok_app.FurniturePurpose', to='Istok_app.purpose'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='colors',
            field=models.ManyToManyField(related_name='colors', through='Istok_app.FurnitureColors', to='Istok_app.color'),
        ),
    ]
