# Generated by Django 4.2 on 2024-10-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0009_alter_survey_new_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-time_created'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки пользователей'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='python_date_time',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Принята', 'Принята'), ('Выполнена', 'Выполнена')], default='Создана', max_length=100, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
    ]
