# Generated by Django 4.2 on 2024-07-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0009_remove_furniture_purpose_furniture_purposes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет мебели', 'verbose_name_plural': 'Все цвета мебели'},
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Мебель', 'verbose_name_plural': 'Вся мебель'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Назначение мебели', 'verbose_name_plural': 'Назначения мебели'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='furniture',
            name='colors',
            field=models.ManyToManyField(related_name='colors', through='Istok_app.FurnitureColors', to='Istok_app.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='purposes',
            field=models.ManyToManyField(related_name='purposes', through='Istok_app.FurniturePurpose', to='Istok_app.purpose', verbose_name='Назначения'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', through='Istok_app.FurnitureTags', to='Istok_app.tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='text',
            field=models.TextField(default='Нет описание мебели', verbose_name='Описание мебели'),
        ),
    ]
