# Generated by Django 4.2 on 2024-10-13 12:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Istok_app', '0010_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_document',
            name='name',
            field=models.CharField(default='Документ №', max_length=400, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выбранная дата для связи'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 13 символов.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
