# Generated by Django 4.2 on 2024-07-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0010_alter_color_options_alter_furniture_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniturecolors',
            name='color',
        ),
        migrations.RemoveField(
            model_name='furniturecolors',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='FurnitureColors',
        ),
    ]
