# Generated by Django 4.2 on 2024-10-13 12:58

import Istok_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0011_order_document_name_alter_application_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order_document',
            name='file',
            field=models.FileField(blank=True, upload_to=Istok_app.models.document_path, verbose_name='Файл'),
        ),
    ]
