# Generated by Django 4.2 on 2024-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0012_order_price_alter_order_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='order',
            name='model_3d',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='3D модель'),
        ),
    ]
