# Generated by Django 4.2 on 2024-07-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0013_remove_projectimage_name_projectimage_image_medium_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
