# Generated by Django 4.2 on 2024-07-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0014_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='image_4',
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.furniture')),
                ('project_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.projectimage')),
            ],
        ),
        migrations.AddField(
            model_name='furniture',
            name='images',
            field=models.ManyToManyField(related_name='images', through='Istok_app.FurnitureImage', to='Istok_app.projectimage', verbose_name='Теги'),
        ),
    ]
