# Generated by Django 4.2 on 2024-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0015_remove_furniture_image_1_remove_furniture_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='only_one_image',
            field=models.BooleanField(blank=True, default=False, verbose_name='Создать только одно изображение'),
        ),
    ]
