# Generated by Django 4.2 on 2024-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0016_projectimage_only_one_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Титульная часть новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='furniture',
            name='tabletop_material',
            field=models.CharField(choices=[('1', 'Столешница ДСП с покрытием HPL'), ('2', 'Столешница компакт-ламинат'), ('3', 'Кварцевая столешница'), ('4', 'Акриловая столешница'), ('5', 'Пластик Fenix')], default='1', max_length=2, verbose_name='Материал столешницы'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='type',
            field=models.CharField(choices=[('1', 'Кухня'), ('2', 'Гардероб'), ('3', 'Стол'), ('4', 'Комод'), ('5', 'Тумбочка'), ('6', 'Шкаф'), ('7', 'Прихожая'), ('8', 'Системы хранения'), ('9', 'Стеллаж')], default='1', max_length=2, verbose_name='Тип мебели'),
        ),
    ]
