# Generated by Django 4.2 on 2024-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0017_news_alter_furniture_tabletop_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='extra_url',
            field=models.URLField(default='', verbose_name='Ссылка на внешний источник'),
        ),
    ]
