# Generated by Django 4.2 on 2024-08-16 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Istok_app', '0018_alter_news_options_news_extra_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150, verbose_name='Номер заказа')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('status', models.CharField(choices=[('1', 'Создан'), ('2', 'Выезд замерщика'), ('3', 'Подготовка эскиза'), ('4', 'Монтаж'), ('5', 'Выполнен'), ('6', 'Отклонен')], default='1', max_length=1, verbose_name='Статус заказа')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('contract', models.FileField(blank=True, upload_to='contracts', verbose_name='Договор')),
                ('model_3d', models.CharField(blank=True, default='<div class="sketchfab-embed-wrapper"> <iframe title="3D" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/b4ec7831bb3e416c841c50b88c1bea16/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/3d-b4ec7831bb3e416c841c50b88c1bea16?utm_medium=embed&utm_campaign=share-popup&utm_content=b4ec7831bb3e416c841c50b88c1bea16" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> 3D </a> by <a href="https://sketchfab.com/ki1004ka?utm_medium=embed&utm_campaign=share-popup&utm_content=b4ec7831bb3e416c841c50b88c1bea16" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Alexander Vasiliev </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=b4ec7831bb3e416c841c50b88c1bea16" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>', max_length=20000, null=True, verbose_name='3D модель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='only_one_image',
            field=models.BooleanField(blank=True, default=False, help_text='Для готовой мебели опцию оставлять отключенной! Для всего остального включать(это сократит занятое место на диске сервера)', verbose_name='Создать только одно изображение'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
    ]
