# Generated by Django 4.2 on 2024-08-20 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0020_alter_order_options_alter_furniture_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Данные заявки ')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Телефон должен быть указан в формате: '+7ХХХХХХХХХХ'. Максимум 13 символов.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Ваш номер телефона')),
                ('contact_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Как с Вами связаться?')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ваша ссылка на Telegram/ВКонтакте')),
                ('date_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата')),
                ('python_date_time', models.DateField(blank=True, null=True, verbose_name='Для теста перевода формата времени из js в python')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='furnitureimage',
            options={'verbose_name': 'Изображение для мебели', 'verbose_name_plural': 'Изображения для мебели'},
        ),
        migrations.AlterModelOptions(
            name='furniturepurpose',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='furnituretags',
            options={'verbose_name': 'Тег мебели', 'verbose_name_plural': 'Теги для мебели'},
        ),
        migrations.AlterModelOptions(
            name='orderimage',
            options={'verbose_name': 'Изображение для заказа', 'verbose_name_plural': 'Изображения для заказа'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='furniture',
            name='images',
            field=models.ManyToManyField(related_name='furniture_images', through='Istok_app.FurnitureImage', to='Istok_app.projectimage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image_medium',
            field=models.ImageField(blank=True, default=None, help_text='Не загружать!', upload_to='', verbose_name='Уменьшенное х2(Загрузка не требуется)'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image_small',
            field=models.ImageField(blank=True, default=None, help_text='Не загружать!', upload_to='', verbose_name='Уменьшенное х5(Загрузка не требуется)'),
        ),
    ]
