# Generated by Django 4.2 on 2024-08-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0023_application_user_alter_application_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория готовой мебели',
                'verbose_name_plural': 'Категории готовой мебели',
            },
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='facades_material',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='form',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='purposes',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='style',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='tabletop_material',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='type',
        ),
        migrations.AddField(
            model_name='furniture',
            name='model_3d',
            field=models.CharField(blank=True, default='В РАЗРАБОТКЕ', max_length=20000, null=True, verbose_name='3D модель готовой мебели'),
        ),
        migrations.DeleteModel(
            name='FurniturePurpose',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Istok_app.furniturecategory', verbose_name='Категория мебели'),
        ),
    ]
