# Generated by Django 4.2 on 2024-09-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Istok_app', '0024_furniturecategory_delete_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ к опроснику',
                'verbose_name_plural': 'Ответы к опроснику',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '(пром. таб.) Вопрос-ответ',
                'verbose_name_plural': '(пром. таб.) Вопрос-ответ',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Опрос пользователя',
                'verbose_name_plural': 'Опросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '(пром. таб.) Опросник-Вопрос',
                'verbose_name_plural': '(пром. таб.) Опросник-Вопрос',
            },
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Мебель', 'verbose_name_plural': 'Готовая мебель для ознакомления'},
        ),
        migrations.AlterField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.furniturecategory', verbose_name='Категория мебели'),
        ),
        migrations.AlterField(
            model_name='news',
            name='extra_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на внешний источник'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='furnitureimage',
            constraint=models.UniqueConstraint(fields=('furniture', 'project_image'), name='furniture_project_image'),
        ),
        migrations.AddConstraint(
            model_name='furnituretags',
            constraint=models.UniqueConstraint(fields=('furniture', 'tag'), name='furniture_tag'),
        ),
        migrations.AddConstraint(
            model_name='orderimage',
            constraint=models.UniqueConstraint(fields=('order', 'order_image'), name='order_order_image'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='question_and_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.questionandanswer'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='answer',
            field=models.ManyToManyField(related_name='questions', through='Istok_app.SurveyAnswer', to='Istok_app.questionandanswer'),
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.option'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='options', through='Istok_app.QuestionOption', to='Istok_app.option'),
        ),
    ]
