# Generated by Django 4.2 on 2024-09-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0025_option_question_questionandanswer_questionoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': '(Тех)Вариант ответа', 'verbose_name_plural': '(Тех)Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос с вариантами ответа', 'verbose_name_plural': 'Вопросы с вариантами ответа'},
        ),
        migrations.AlterModelOptions(
            name='questionandanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='surveyanswer',
            options={'verbose_name': '(Тех)Опросник-Вопрос', 'verbose_name_plural': '(Тех)Опросник-Вопрос'},
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.question', verbose_name='Вопрос'),
        ),
    ]
