# Generated by Django 4.2 on 2024-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0028_alter_survey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question_and_answer',
        ),
        migrations.AddField(
            model_name='survey',
            name='question_and_answers',
            field=models.ManyToManyField(related_name='question_and_answers', through='Istok_app.SurveyAnswer', to='Istok_app.questionandanswer'),
        ),
    ]
