# Generated by Django 4.2 on 2024-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0029_remove_survey_question_and_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multy_choice',
            field=models.BooleanField(default=False, help_text='При включении этой опции позволяет опрашиваемому выбрать несколько вариантов', verbose_name='Выбрать несколько ответов (Да/Нет)'),
        ),
    ]
