# Generated by Django 4.2 on 2024-09-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0030_question_multy_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('user_answer', models.BooleanField(default=False, help_text='Если True, то вариант был написан пользователем', verbose_name='Ответ написан пользователем')),
            ],
            options={
                'verbose_name': '(Тех)Ответ пользователя',
                'verbose_name_plural': '(Тех)Ответы пользователя',
            },
        ),
        migrations.RenameModel(
            old_name='SurveyAnswer',
            new_name='SurveyQuestionAndAnswer',
        ),
        migrations.AlterModelOptions(
            name='questionandanswer',
            options={'verbose_name': '(Тех)Вопрос-Ответ', 'verbose_name_plural': '(Тех)Вопросы-Ответы'},
        ),
        migrations.RemoveField(
            model_name='questionandanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='option',
            name='user_input',
            field=models.BooleanField(default=False, help_text='Если True, пользователь сможет ввести свой вариант ответа', verbose_name='Вариант пользователя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='multy_choice',
            field=models.BooleanField(default=False, help_text='При включении этой опции позволяет опрашиваемому выбрать несколько вариантов', verbose_name='Выбрать несколько ответов'),
        ),
        migrations.CreateModel(
            name='AnswerQuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.answer')),
                ('question_and_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Istok_app.questionandanswer')),
            ],
            options={
                'verbose_name': '(Тех)Опросник-Вопрос',
                'verbose_name_plural': '(Тех)Опросник-Вопрос',
            },
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='answers',
            field=models.ManyToManyField(related_name='answers', through='Istok_app.AnswerQuestionAndAnswer', to='Istok_app.answer'),
        ),
    ]
