# Generated by Django 4.2 on 2024-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0031_answer_rename_surveyanswer_surveyquestionandanswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '(Тех)Answer', 'verbose_name_plural': '(Тех)Answers'},
        ),
        migrations.AlterModelOptions(
            name='answerquestionandanswer',
            options={'verbose_name': '(m2m)AnswerQuestionAndAnswer', 'verbose_name_plural': '(m2m)AnswerQuestionAndAnswers'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': '(Тех)Option', 'verbose_name_plural': '(Тех)Options'},
        ),
        migrations.AlterModelOptions(
            name='questionandanswer',
            options={'verbose_name': '(Тех)QuestionAndAnswer', 'verbose_name_plural': '(Тех)QuestionAndAnswers'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='surveyquestionandanswer',
            options={'verbose_name': '(m2m)Ответ на вопрос', 'verbose_name_plural': '(m2m)Ответы на вопросы'},
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст варианта ответа'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата опроса'),
        ),
    ]
