# Generated by Django 4.2 on 2024-09-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0032_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_was_changed',
            field=models.BooleanField(default=False, help_text='Данный статус автоматически изменяется если были изменения в опроснике(как случай, добавление новых вопросов)\nЕсли есть новые вопросы пользователь должен будет вновь пройти опрос', verbose_name='Опросник был изменен'),
        ),
    ]
