# Generated by Django 4.2 on 2024-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0033_survey_survey_was_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_filling_duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность заполнения опросника.'),
        ),
    ]
