# Generated by Django 4.2 on 2024-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0034_survey_survey_filling_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_write_time', models.PositiveIntegerField(default=30, help_text='Минимальное количество времени, требуемое для заполнение опросника. Если опросник был заполнен быстрее, он будет помечен как неблагонадежный. Неблагонадежные опросники будут исключаться из аналитики.', verbose_name='Мин. время заполнения опросника(сек)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='dependable',
            field=models.BooleanField(default=True, help_text='Статус становится положительным в случае если опросник заполняли больше минимального времени заполнения. При аналитике ненадежные будут вычеркиваться из выборки', verbose_name='Статус надежности опросника'),
        ),
        migrations.AddField(
            model_name='survey',
            name='min_write_time',
            field=models.PositiveIntegerField(default=30, help_text='Минимальное количество времени, требуемое для заполнение опросника. Если опросник был заполнен быстрее, он будет помечен как неблагонадежный', verbose_name='Мин. время заполнения(сек)'),
        ),
    ]
