# Generated by Django 4.2 on 2024-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0036_websitesettings_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='name',
            field=models.CharField(blank=True, default='Все настройки', max_length=100),
        ),
    ]
