# Generated by Django 4.2 on 2024-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0037_websitesettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='min_write_time',
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='name',
            field=models.CharField(blank=True, default='Все настройки', max_length=100, verbose_name=''),
        ),
    ]
