# Generated by Django 4.2 on 2024-09-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0038_remove_survey_min_write_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='survey_filling_duration',
        ),
    ]
