# Generated by Django 4.2 on 2024-09-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0039_remove_survey_survey_filling_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
    ]
