# Generated by Django 4.2 on 2024-09-17 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Istok_app', '0041_survey_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_was_changed',
            new_name='questions_was_changed',
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
