# Generated by Django 4.2 on 2024-09-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0043_remove_surveyquestionandanswer_question_and_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions_was_changed',
            field=models.BooleanField(blank=True, default=False, help_text='Данный статус автоматически изменяется если были изменения в опроснике(как случай, добавление новых вопросов)\nЕсли есть новые вопросы пользователь должен будет вновь пройти опрос', verbose_name='Опросник был изменен'),
        ),
    ]
