# Generated by Django 4.2 on 2024-09-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_loyalty_new_befits'),
        ('Istok_app', '0044_alter_survey_questions_was_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.loyalty'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model_3d',
            field=models.CharField(blank=True, default='3d code', max_length=20000, null=True, verbose_name='3D модель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Выезд замерщика', 'Выезд замерщика'), ('Подготовка эскиза', 'Подготовка эскиза'), ('Монтаж', 'Монтаж'), ('Выполнен', 'Выполнен'), ('Отклонен', 'Отклонен')], default='1', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
