# Generated by Django 4.2 on 2024-09-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0045_order_loyalty_code_alter_order_model_3d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='loyalty_code',
            field=models.CharField(blank=True, default=None, help_text='Если покупатель совершает заказ с использованием чужого кода лояльности, владелец кода автоматически оповещается о возможности выбора выгоды', max_length=5, null=True, verbose_name='Чужой код лояльности'),
        ),
    ]
