# Generated by Django 4.2 on 2024-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0046_alter_order_loyalty_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
