# Generated by Django 4.2 on 2024-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0047_alter_furniture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='Istok_app.furniture', verbose_name='Список рекомендаций'),
        ),
    ]
