# Generated by Django 4.2 on 2024-09-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0048_furniture_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='recommendations',
        ),
    ]
