# Generated by Django 4.2 on 2024-09-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Istok_app', '0049_remove_furniture_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_furniture', to='Istok_app.furniture')),
                ('similar_furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_furniture', to='Istok_app.furniture')),
            ],
            options={
                'verbose_name': 'Рекомендовать к этой мебели',
                'verbose_name_plural': 'Рекомендовать к этой мебели',
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='recommendations',
            field=models.ManyToManyField(blank=True, through='Istok_app.SimilarFurniture', to='Istok_app.furniture', verbose_name='Список рекомендаций'),
        ),
    ]
